[project]
name = "peekaboo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "~=3.12.0"
dependencies = []

[project.optional-dependencies]
code-agent = [
  "specify-cli",
  "serena-agent>=0.1"
]

[tool.uv.sources]
specify-cli = { git = "https://github.com/github/spec-kit.git" }
serena-agent = { git = "https://github.com/oraios/serena.git" }